# fly.toml app configuration file generated for youtubedownloader-frontend-restless-star-9831 on 2025-03-06T10:59:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'youtubedownloader-frontend-restless-star-9831'
primary_region = 'gru'

[build]

[env]
  REACT_APP_API_URL = 'https://youtubedownloader-backend.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
