
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


primary_region = 'gru'

[build]

[http_service]

  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

